import styled, { createGlobalStyle } from "styled-components";

export const Global = createGlobalStyle`
  body {
    margin: 0;
    background-color: #FFFFFF;
  }`

  export const Contact=styled.div`
  width: 225px;
  height:60px;
  position: sticky; /* Ustawienie kontenera jako pozycja stała */
  margin-top:10px;
  margin-left:auto;
  margin-right: 0;
  font-weight: 500;
  color:black;
  font-size: 20px;
  top:30px;
  z-index:2;
  display: flex;
  align-items: flex-end;
  border-bottom:1px solid black;
  :hover{
    cursor: pointer;
    transition: ease-in-out 200ms;
    font-style: italic;
    font-size: 17px;
    font-weight:400;
  }
  @media  screen and (max-width: 768px) {


  }
  
  `
  export const Textcontainerfirst=styled.div`
  width: 1350px;
  height: 200px;
  display: flex;
  align-items: end;
  margin-top: 60px;
  justify-content: space-between;
  font-size: 170px;
  font-weight: 600;
  color:black;
  margin-bottom: 0;
  margin-left:auto;
  margin-right: 0;
  border-bottom:1px solid black;
  -webkit-animation: slide-in-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
            /* ----------------------------------------------
 * Generated by Animista on 2024-4-28 17:10:24
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@media  screen and (max-width: 768px) {
width: 360px;
height: 49px;
font-size: 55px;

    
}
 `
 export const Iconphoto=styled.img`
 width: 100px;
 height: 100px;
 
 margin-right: 140px;
 margin-bottom: 20px;
 @media  screen and (max-width: 768px) {
width: 54px;
height: 54px;
margin-bottom: 0;
margin-left: 80px;
 }
 `
 export const Textcontainersecond=styled.div`
 width:850px;
 height:200px;
 border-bottom: 1px solid black;
 font-weight: 600;
 font-size: 170px;
 color:black;
 margin-left:auto;
  margin-right: 0;
  -webkit-animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
           /* ----------------------------------------------
 * Generated by Animista on 2024-5-1 23:25:4
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@media  screen and (max-width: 768px) {
width: 275px;
height: 63px;
font-size: 55px;
font-weight: 600;
    
}

 `
 export const Textcontainerthird=styled.div`
  width: 1350px;
  height: 200px;
  display: flex;
  align-items: end;
  font-size: 170px;
  font-weight: 300;
  color:black;
  margin-left:auto;
  margin-right: 0;
  border-bottom:1px solid black;
  display: flex;
  align-items: end;
  -webkit-animation: slide-in-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
            /* ----------------------------------------------
 * Generated by Animista on 2024-4-28 17:10:24
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@media  screen and (max-width: 768px) {
width: 360px;
height: 49px;
font-size: 55px;
margin-top: 20px;
    
}
 `

 export const Textcontainerfour=styled.div`
 width:850px;
 height:200px;
 border-bottom: 1px solid black;
 font-weight: 300;
 font-size: 150px;
 color:black;
 margin-left:auto;
  margin-right: 0;
 display: flex;
 align-items: end;
 font-style: italic;
 -webkit-animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
           /* ----------------------------------------------
 * Generated by Animista on 2024-5-1 23:25:4
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@media  screen and (max-width: 768px) {
width: 275px;
height: 63px;
font-size: 55px;
font-weight: 300;
    
}

`

export const Firstcontainercontent=styled.div`

width:1200px;
height:800px;
margin-left: auto;
margin-right: auto;
margin-top: 150px;

display:flex;
justify-content:space-around;
margin-bottom: 150px;
@media  screen and (max-width: 768px) {
    display: flex;
    flex-direction: column;
}
`
export const Firstcontainerinside=styled.div`
width:730px;
height: 800px;

z-index: 1;

`
export const Miloszimage=styled.img`
width: 618px;
height: 800px;

&:hover{

    scale:1.5;
}
`
export const Firstparagraph=styled.div`
width:160%;
height:110px;
border-bottom: 1px solid black;
font-size: 100px;
font-weight:500;

display: flex;
justify-content: flex-start;
`
export const Secondparagraph=styled.div`
width:100%;
height:110px;
border-bottom: 1px solid black;
font-size: 100px;
font-weight:500;
`
export const Thirdparagraph=styled.div`
width:130%;
height:110px;
border-bottom: 1px solid black;
font-size: 100px;
font-weight:500;

span{
    color:white;
    border-bottom:none;
}
`
export const Fourparagraph=styled.div`

width:468px;
height:184px ;
font-size: 16px;
font-weight: 500;
margin-top: 100px;
`
export const Firstacapit=styled.div`
margin-left: auto;
margin-right: 0;
width: 1350px;
height:110px;
border-bottom: 1px solid black;
font-size:100px;
font-weight:500;
`

export const Containerphototext=styled.div`
width:1200px;
height:auto;
margin-left:auto;
margin-right: auto;

margin-top: 200px;
display:flex;
justify-content: space-between;

`
export const Containertxt=styled.div`
width:270px;
height:285px;

font-size: 16px;
font-weight:600;
margin-top: 0;
p{
    
    margin-top: 0;
}
`
export const Containeryeyes=styled.div`
width:150px;
height:50px;
z-index:5;

position: absolute;
  bottom: 0;
  left:2%;
  display: flex;
  justify-content: flex-start;
  align-items: center;
  
`
export const Eyeimg=styled.div`
width: 15px;
height:15px;
background-color: gray;
border-radius:50%;
margin-left:5px;
border:1px solid white;

&:hover{
    background-color: white;
    cursor:pointer;
}

`

export const Lastbigcontainer=styled.div`
width: 1200px;
margin-left: auto;
margin-right: auto;
height:500px;

display: flex;
justify-content: space-between;
margin-top: 300px;
`
export const Fotter=styled.div`

width: 1200px;
height:100px;
display: flex;
justify-content: space-between;

margin-top: 100px;
margin-left: auto;
margin-right:auto ;
`
export const Firstelementfotter=styled.div`
width: 370px;
height: 22px;
font-size: 16px;
font-weight: 500;

`
export const Secondelementfotter=styled.div`
width:370px;
height:82px;
font-size:16px;
font-weight:500;
text-align: center;

text-transform: uppercase;
`
export const Thirdelementfotter=styled.div`
width: 370px;
height: 82px;
font-size: 16px;
font-weight: 500;
display: flex;
justify-content: flex-end;
`
export const Leftcontainer=styled.div`
width: 750px;
height:500px;

`
export const Miloszsmile=styled.img`
height: 500px;
width:450px;
`
export const Textwithunderline=styled.div`
width: 750px;
height:100px;
font-size:100px;
font-weight: 600;
border-bottom:1px solid black;
display: flex;
align-items: center;
`
export const Containerwithcontact=styled.div`
width:700px;
height:80px;

margin-top: 100px;
display: flex;
justify-content: space-between;
`
export const Writeonemail=styled.div`
width:370px;
height:80px;

margin-top: 0;
font-size:20px ;
font-weight: 600;
p{
    margin-top: 0;
   
    margin-bottom: 0;
}
`
export const Localization=styled.div`
width: 230px;
height: 80px;

margin-top: 0;
font-size:20px ;
font-weight: 600;
p{
    margin-top: 0;
    
    margin-bottom: 0;
}
`
export const Containersocialmedia=styled.div`
width: 100px;
height:30px;

margin-top: 83px;
display: flex;
justify-content: space-between;
`
export const InstagramandBe=styled.img`
width: 30px;
height:30px;
&:hover{
    scale: 1.4;
}
`

