import styled, { createGlobalStyle } from "styled-components";

export const Global = createGlobalStyle`
  body {
    margin: 0;
    background-color: #FFFFFF;
  }@media  screen and (max-width: 768px) {
    overflow-x: hidden;
    width: 100vw;

  }
  
  `

  export const Contact=styled.div`
  width: 225px;
  height:60px;
  position: sticky; /* Ustawienie kontenera jako pozycja stała */
  margin-top:10px;
  margin-left:auto;
  margin-right: 0;
  font-weight: 500;
  color:black;
  font-size: 20px;
  top:30px;
  z-index:2;
  display: flex;
  align-items: flex-end;
  border-bottom:1px solid black;
  :hover{
    cursor: pointer;
    transition: ease-in-out 200ms;
    font-style: italic;
    font-size: 17px;
    font-weight:400;
  }
  @media  screen and (max-width: 768px) {
width: 45%;
margin-bottom: 100px;



  } @media  screen and (min-width: 768px) and (max-width: 1024px) {

    width: 45%;
    margin-bottom:300px;
    margin-left:auto;
  margin-right: 0;
  font-size: 25px;
  }
  @media  screen and (min-width: 1024px) {
    width: 45%;
    margin-bottom:300px;
    margin-left:auto;
  margin-right: 0;
  font-size: 25px;
  }
  `
  export const Textcontainerfirst=styled.div`
  width: 1350px;
  height: 200px;
  display: flex;
  align-items: end;
  margin-top: 60px;
  justify-content: space-between;
  font-size: 170px;
  font-weight: 600;
  color:black;
  margin-bottom: 0;
  margin-left:auto;
  margin-right: 0;
  border-bottom:1px solid black;
  -webkit-animation: slide-in-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
            /* ----------------------------------------------
 * Generated by Animista on 2024-4-28 17:10:24
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@media  screen and (max-width: 768px) {
width: 85%;
height: 49px;
font-size: 55px;

    
} @media  screen and (min-width: 768px) and (max-width: 1024px) {

  width: 85%;
height: 49px;
font-size: 55px;

}
@media  screen and (min-width: 1024px) {
  width: 85%;
height: 49px;
font-size: 55px;
}
 `
 export const Iconphoto=styled.img`
 width: 100px;
 height: 100px;
 
 margin-right: 140px;
 margin-bottom: 20px;
 @media  screen and (max-width: 768px) {
width: 54px;
height: 54px;
margin-bottom: 0;
margin-left: 80px;

 }@media  screen and (min-width: 768px) and (max-width: 1024px) {

  width: 74px;
height: 74px;
margin-bottom: 0;
margin-left: 80px;

 }
 @media  screen and (min-width: 1024px) {
  width: 74px;
height: 74px;
margin-bottom: 0;
margin-left: 80px;
 }

 `
 export const Textcontainersecond=styled.div`
 width:850px;
 height:200px;
 border-bottom: 1px solid black;
 font-weight: 600;
 font-size: 170px;
 color:black;
 margin-left:auto;
  margin-right: 0;
  -webkit-animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
           /* ----------------------------------------------
 * Generated by Animista on 2024-5-1 23:25:4
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@media  screen and (max-width: 768px) {
width: 70%;
height: 63px;
font-size: 55px;
font-weight: 600;
    
}
@media  screen and (min-width: 768px) and (max-width: 1024px) {
  width: 70%;
height: 63px;
font-size: 55px;
font-weight: 600;
}
@media  screen and (min-width: 1024px) {
  width: 70%;
height: 63px;
font-size: 55px;
font-weight: 600;
}
 `
 export const Textcontainerthird=styled.div`
  width: 1350px;
  height: 200px;
  display: flex;
  align-items: end;
  font-size: 170px;
  font-weight: 300;
  color:black;
  margin-left:auto;
  margin-right: 0;
  border-bottom:1px solid black;
  display: flex;
  align-items: end;
  -webkit-animation: slide-in-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
            /* ----------------------------------------------
 * Generated by Animista on 2024-4-28 17:10:24
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@media  screen and (max-width: 768px) {
width: 85%;
height: 49px;
font-size: 55px;
margin-top: 20px;
    
}
@media  screen and (min-width: 768px) and (max-width: 1024px) {

  width: 85%;
height: 49px;
font-size: 55px;
margin-top: 20px;
}
@media  screen and (min-width: 1024px) {
  width: 85%;
height: 49px;
font-size: 55px;
margin-top: 20px;
}
 `

 export const Textcontainerfour=styled.div`
 width:850px;
 height:200px;
 border-bottom: 1px solid black;
 font-weight: 300;
 font-size: 150px;
 color:black;
 margin-left:auto;
  margin-right: 0;
 display: flex;
 align-items: end;
 font-style: italic;
 -webkit-animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
           /* ----------------------------------------------
 * Generated by Animista on 2024-5-1 23:25:4
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@media  screen and (max-width: 768px) {
width: 75%;
height: 63px;
font-size: 55px;
font-weight: 300;
  
}

@media  screen and (min-width: 768px) and (max-width: 1024px) {
  width: 75%;
height: 63px;
font-size: 55px;
font-weight: 300;

}
@media  screen and (min-width: 1024px) {
  width: 75%;
height: 63px;
font-size: 55px;
font-weight: 300;
}
`

export const Firstcontainercontent=styled.div`

width:1200px;
height:800px;
margin-left: auto;
margin-right: auto;
margin-top: 150px;

display:flex;
justify-content:space-around;
margin-bottom: 150px;
@media  screen and (max-width: 768px) {
    display: flex;
    flex-direction: column;
    
    width: 100%;
    height:auto;
    
}
@media  screen and (min-width: 768px) and (max-width: 1024px) {

  display: flex;
    flex-direction: column;
    
    width: 100vw;
    height:auto;

}
`
export const Firstcontainerinside=styled.div`
width:730px;
height: 800px;

z-index: 1;
@media  screen and (max-width: 768px) {
  
  width: 100vw;
  height:450px;
}
@media  screen and (min-width: 768px) and (max-width: 1024px) {
  width: 100vw;
  height:450px;

}

`
export const Miloszimage=styled.img`
width: 618px;
height: 800px;

&:hover{

    opacity: 0.7;
}
@media  screen and (max-width: 768px) {
  width: 95vw;
  height:416px;
  margin-left: auto;
  margin-right: auto;
  position: relative;
  bottom: 300px;
}@media  screen and (min-width: 768px) and (max-width: 1024px) {
  width: 95vw;
  height:416px;
  margin-left: auto;
  margin-right: auto;
  position: relative;
  bottom: 300px;
}

`
export const Firstparagraph=styled.div`
width:160%;
height:110px;
border-bottom: 1px solid black;
font-size: 100px;
font-weight:500;

display: flex;
justify-content: flex-start;
@media  screen and (max-width: 768px) {
  width: 95%;
  height:38px;
  font-size: 33px;
  margin-left: auto;
  margin-right: 0;
  
}@media  screen and (min-width: 768px) and (max-width: 1024px) {
  width: 95%;
  height:38px;
  font-size: 33px;
  margin-left: auto;
  margin-right: 0;

}

`
export const Secondparagraph=styled.div`
width:100%;
height:110px;
border-bottom: 1px solid black;
font-size: 100px;
font-weight:500;
@media  screen and (max-width: 768px) {
  width: 95%;
  height:38px;
  font-size: 33px;
  margin-left: auto;
  margin-right: 0;
  
}@media  screen and (min-width: 768px) and (max-width: 1024px) {
  width: 95%;
  height:38px;
  font-size: 33px;
  margin-left: auto;
  margin-right: 0;

}
`
export const Thirdparagraph=styled.div`
width:130%;
height:110px;
border-bottom: 1px solid black;
font-size: 100px;
font-weight:500;

span{
    color:white;
    border-bottom:none;
}
@media  screen and (max-width: 768px) {
  width: 95%;
  height:38px;
  font-size: 33px;
  margin-left: auto;
  margin-right: 0;
  span{
    color:black;
  }
}@media  screen and (min-width: 768px) and (max-width: 1024px) {
  width: 95%;
  height:38px;
  font-size: 33px;
  margin-left: auto;
  margin-right: 0;
  span{
    color:black;
  }
}
`
export const Fourparagraph=styled.div`

width:468px;
height:184px ;
font-size: 16px;
font-weight: 500;
margin-top: 100px;
@media  screen and (max-width: 768px) {
  width: 95%;
  height:176px;
  font-size: 16px;
  margin-left: auto;
  margin-right: auto; 
  
  position: relative;
  top:380px;
  
  
}@media  screen and (min-width: 768px) and (max-width: 1024px) {
  width: 95%;
  height:176px;
  font-size: 16px;
  margin-left: auto;
  margin-right: auto; 
  
  position: relative;
  top:380px;
}
`
export const Firstacapit=styled.div`
margin-left: auto;
margin-right: 0;
width: 1350px;
height:110px;
border-bottom: 1px solid black;
font-size:100px;
font-weight:500;
@media  screen and (max-width: 768px) {
width: 80%;
margin-left: auto;
margin-right: 0;
height: auto;

font-size: 33px;
overflow-x: hidden;
}@media  screen and (min-width: 768px) and (max-width: 1024px) {
  width: 80%;
margin-left: auto;
margin-right: 0;
height: auto;

font-size: 33px;
overflow-x: hidden;
}
`

export const Containerphototext=styled.div`
width:1200px;
height:auto;
margin-left:auto;
margin-right: auto;

margin-top: 200px;
display:flex;
justify-content: space-between;
@media  screen and (max-width: 768px) {
  width: 100%;
  height:auto;
  display:flex;
  margin-top: 50px;
  flex-direction: column;
  &:nth-of-type(odd) {
    @media screen and (max-width: 768px) {
      flex-direction: column-reverse;
    }
  }
  
}@media  screen and (min-width: 768px) and (max-width: 1024px) {
  width: 100%;
  height:auto;
  display:flex;
  margin-top: 50px;
  flex-direction: column;
  &:nth-of-type(odd) {
    @media screen and  (min-width: 768px) and (max-width: 1024px) {
      flex-direction: column-reverse;
    }
  }
}

`
export const Containertxt=styled.div`
width:270px;
height:285px;

font-size: 16px;
font-weight:600;
margin-top: 0;
p{
    
    margin-top: 0;
}
@media  screen and (max-width: 768px) {
  width: 100%;
  margin-top: 20px;
  height: 264px;
  font-size: 16px;
}
@media screen and  (min-width: 768px) and (max-width: 1024px) {
  width: 100%;
  margin-top: 20px;
  height: 264px;
  font-size: 16px;
}
`
export const Containeryeyes=styled.div`
width:150px;
height:50px;
z-index:5;

position: absolute;
  bottom: 0;
  left:2%;
  display: flex;
  justify-content: flex-start;
  align-items: center;
  
`
export const Eyeimg=styled.div`
width: 15px;
height:15px;
background-color: gray;
border-radius:50%;
margin-left:5px;
border:1px solid white;

&:hover{
    background-color: white;
    cursor:pointer;
}

`

export const Lastbigcontainer=styled.div`
width: 1200px;
margin-left: auto;
margin-right: auto;
height:500px;

display: flex;
justify-content: space-between;
margin-top: 300px;
@media  screen and (max-width: 768px) {
  
  display: flex;
  flex-direction: column;
  width: 100vw;
}@media screen and  (min-width: 768px) and (max-width: 1024px) {
  display: flex;
  flex-direction: column;
  width: 100vw;
}
`
export const Fotter=styled.div`

width: 1200px;
height:100px;
display: flex;
justify-content: space-between;
@media  screen and (max-width: 768px) {
  width: 90%;
  height: 80px;
  position:relative;
  top:100%;  
  
  margin-left: auto;
  margin-right: auto;
}

margin-top: 100px;
margin-left: auto;
margin-right:auto ;
@media screen and  (min-width: 768px) and (max-width: 1024px) {
  width: 90%;
  height: 80px;
  position:relative;
  top:100%;  
  
  margin-left: auto;
  margin-right: auto;
}
`
export const Firstelementfotter=styled.div`
width: 370px;
height: 22px;
font-size: 16px;
font-weight: 500;
@media  screen and (max-width: 768px) {
  font-size: 16px;
  
  width: 160px;
}
@media screen and  (min-width: 768px) and (max-width: 1024px) {
  font-size: 16px;
  
  width: 160px;
}
`
export const Secondelementfotter=styled.div`
width:370px;
height:82px;
font-size:16px;
font-weight:500;
text-align: center;
text-transform: uppercase;
@media  screen and (max-width: 768px) {
  font-size: 16px;
 
  text-transform: lowercase;
  width: 200px;
  
 width: 150px;
 height: 30px;
 position: relative;
 top:30%;
 right:46%;
 text-align: start;
}
@media screen and  (min-width: 768px) and (max-width: 1024px) {
  font-size: 16px;
 
  text-transform: lowercase;
  width: 200px;
  
 width: 150px;
 height: 30px;
 position: relative;
 top:30%;
 right:46%;
 text-align: start;
}
`
export const Thirdelementfotter=styled.div`
width: 370px;
height: 82px;
font-size: 16px;
font-weight: 500;
display: flex;
justify-content: flex-end;
@media  screen and (max-width: 768px) {
  position: relative;
  top:30%;
  
  width:40px;
  height: 50px;

}
@media screen and  (min-width: 768px) and (max-width: 1024px) {
  position: relative;
  top:30%;
  
  width:40px;
  height: 50px;
}
`
export const Leftcontainer=styled.div`
width: 750px;
height:500px;
@media  screen and (max-width: 768px) {
  
  width: 100vw;
}
@media screen and  (min-width: 768px) and (max-width: 1024px) {
  width: 100vw;
}
`
export const Miloszsmile=styled.img`
height: 500px;
width:450px;
@media  screen and (max-width: 768px) {
 
  position: relative;
  bottom: 125%;
  width: 90vw;
  margin-left: auto;
  margin-right: auto;

  
}
@media screen and  (min-width: 768px) and (max-width: 1024px) {
  position: relative;
  bottom: 125%;
  width: 90vw;
  margin-left: auto;
  margin-right: auto;

}
`
export const Textwithunderline=styled.div`
width: 750px;
height:100px;
font-size:100px;
font-weight: 600;
border-bottom:1px solid black;
display: flex;
align-items: center;
@media  screen and (max-width: 768px) {
  
 position: relative;
 bottom: 90%;
 width: 95vw;
 height:68px;
 font-size:66px;
 font-weight: 500;
 margin-left: auto;
 margin-right: 0;
 
}
@media screen and  (min-width: 768px) and (max-width: 1024px) {
  position: relative;
 bottom: 90%;
 width: 95vw;
 height:68px;
 font-size:66px;
 font-weight: 500;
 margin-left: auto;
 margin-right: 0;
}
`
export const Containerwithcontact=styled.div`
width:700px;
height:80px;

margin-top: 100px;
display: flex;
justify-content: space-between;
@media  screen and (max-width: 768px) {
  
  display: flex;
  flex-direction: column;
  width: 90vw;
  position: relative;
  top:5%;
  margin-left: auto;
  margin-right: auto;
  font-size: 16px;
}
@media screen and  (min-width: 768px) and (max-width: 1024px) {
  display: flex;
  flex-direction: column;
  width: 90vw;
  position: relative;
  top:5%;
  margin-left: auto;
  margin-right: auto;
  font-size: 16px;
}
`
export const Writeonemail=styled.div`
width:370px;
height:80px;
font-size: 16px;
margin-top: 0;
font-size:20px ;
font-weight: 600;
p{
    margin-top: 0;
   
    margin-bottom: 0;
}
@media  screen and (max-width: 768px) {
position: relative;
top:50%;
margin-top: 20px;
}
@media screen and  (min-width: 768px) and (max-width: 1024px) {
  position: relative;
top:50%;
margin-top: 20px;
}
`
export const Localization=styled.div`
width: 230px;
height: 80px;

margin-top: 0;
font-size:20px ;
font-weight: 600;
p{
    margin-top: 0;
    
    margin-bottom: 0;
}
@media  screen and (max-width: 768px) {
position: relative;
top:50%;
margin-top: 20px;
}
@media screen and  (min-width: 768px) and (max-width: 1024px) {
  position: relative;
top:50%;
margin-top: 20px;
}
`
export const Containersocialmedia=styled.div`
width: 100px;
height:30px;

margin-top: 83px;
display: flex;
justify-content: space-between;
@media  screen and (max-width: 768px) {
position: relative;
top:18%;

left:5%;
}
@media screen and  (min-width: 768px) and (max-width: 1024px) {
  position: relative;
top:18%;

left:5%;
}
`
export const InstagramandBe=styled.img`
width: 30px;
height:30px;
&:hover{
    scale: 1.4;
}
`

